// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Systekna.Application.Business;

#nullable disable

namespace WbCoreAPI.Migrations
{
    [DbContext(typeof(BbApplication))]
    [Migration("20231104141243_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Systekna.Core.ModelFinanceiro", b =>
                {
                    b.Property<int?>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("ID"));

                    b.Property<string>("DsDespesa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DtAlteração")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DtCriação")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DtExclusão")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DtVencimento")
                        .HasColumnType("datetime2");

                    b.Property<bool>("FlExclusão")
                        .HasColumnType("bit");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("VlrDespesa")
                        .HasColumnType("decimal(12, 2)");

                    b.HasKey("ID");

                    b.ToTable("TB_DESPESA");
                });
#pragma warning restore 612, 618
        }
    }
}
